services:
  postgres:
    container_name: what_the_hill_db
    image: postgres
    environment:
      POSTGRES_DB: what_the_hill
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres:
